version: '3'

x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  app:
    <<: *restart_policy
    build:
      context: .
    env_file:
      - .env
    ports:
      - "${APP_PORT}:80"